openapi: 3.0.0
servers:
  - url: http://xkcd.com/
info:
  description: Webcomic of romance, sarcasm, math, and language.
  title: XKCD
  version: 1.0.0
paths:
  /info.0.json:
    get:
      description: |
        Fetch current comic and metadata.
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/comic"
          description: OK
components:
  schemas:
    comic:
      x-flow-type:
          name: comic
      x-flow-query:
          path: /info.0.json
          operation: get    
      properties:
        alt:
          type: string
        day:
          type: string
        img:
          type: string
        link:
          type: string
        month:
          type: string
        news:
          type: string
        num:
          type: integer
        safe_title:
          type: string
        title:
          type: string
        transcript:
          type: string
        year:
          type: string